FROM earthakkharawat/capstone_env:2.0 AS build
COPY . .

# Runtime stage
# FROM huggingface/optimum-nvidia
# COPY --from=build . .
RUN pip install fastapi
RUN pip install bitsandbytes
EXPOSE 8001
CMD ["python3", "main.py"]